// <auto-generated />
using System;
using Holod.Models.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Holod.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("Holod.Models.Database.Coordinates", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Latitude");

                    b.Property<double>("Longitude");

                    b.HasKey("Id");

                    b.ToTable("Coordinates");
                });

            modelBuilder.Entity("Holod.Models.Database.Hostel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<int?>("CoordinatesId");

                    b.Property<int>("NumberFloors");

                    b.Property<int>("NumberStudents");

                    b.Property<string>("Phone");

                    b.Property<string>("Photo");

                    b.Property<double>("Rating");

                    b.Property<int>("StudentCityId");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("CoordinatesId");

                    b.HasIndex("StudentCityId");

                    b.ToTable("Hostels");
                });

            modelBuilder.Entity("Holod.Models.Database.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("StuffId");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("StuffId")
                        .IsUnique();

                    b.ToTable("Post");
                });

            modelBuilder.Entity("Holod.Models.Database.Resident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Firstname");

                    b.Property<int?>("HostelId");

                    b.Property<string>("NumberRoom");

                    b.Property<string>("Patronymic");

                    b.Property<string>("Photo");

                    b.Property<string>("Surname");

                    b.HasKey("Id");

                    b.HasIndex("HostelId");

                    b.ToTable("Residents");
                });

            modelBuilder.Entity("Holod.Models.Database.StudentCity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Photo");

                    b.HasKey("Id");

                    b.ToTable("StudentCities");
                });

            modelBuilder.Entity("Holod.Models.Database.Stuff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Firstname");

                    b.Property<int?>("HostelId");

                    b.Property<string>("Patronymic");

                    b.Property<string>("Photo");

                    b.Property<int?>("StudentCityId");

                    b.Property<string>("Surname");

                    b.HasKey("Id");

                    b.HasIndex("HostelId");

                    b.HasIndex("StudentCityId");

                    b.ToTable("Stuffs");
                });

            modelBuilder.Entity("Holod.Models.Database.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Login");

                    b.Property<string>("Password");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Holod.Models.Database.Hostel", b =>
                {
                    b.HasOne("Holod.Models.Database.Coordinates", "Coordinates")
                        .WithMany()
                        .HasForeignKey("CoordinatesId");

                    b.HasOne("Holod.Models.Database.StudentCity", "StudentCity")
                        .WithMany("Hostels")
                        .HasForeignKey("StudentCityId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Holod.Models.Database.Post", b =>
                {
                    b.HasOne("Holod.Models.Database.Stuff", "Stuff")
                        .WithOne("Post")
                        .HasForeignKey("Holod.Models.Database.Post", "StuffId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Holod.Models.Database.Resident", b =>
                {
                    b.HasOne("Holod.Models.Database.Hostel", "Hostel")
                        .WithMany("Residents")
                        .HasForeignKey("HostelId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Holod.Models.Database.Stuff", b =>
                {
                    b.HasOne("Holod.Models.Database.Hostel", "Hostel")
                        .WithMany("Stuffs")
                        .HasForeignKey("HostelId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Holod.Models.Database.StudentCity", "StudentCity")
                        .WithMany("Stuffs")
                        .HasForeignKey("StudentCityId");
                });
#pragma warning restore 612, 618
        }
    }
}
